version: '3.8'

services:
  # Loki 日志服务
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - loki-network
    environment:
      - TZ=Asia/Shanghai

  # Grafana 可视化
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - TZ=Asia/Shanghai
    depends_on:
      - loki
    networks:
      - loki-network

volumes:
  loki-data:
  grafana-data:

networks:
  loki-network:
    driver: bridge

