[project]
name = "miniwow-levelup-air"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "airtest>=1.3.6",
    "coloredlogs>=15.0.1",
]
